services:
    phlexible_country_context.country_collection:
        class: Phlexible\Bundle\CountryContextBundle\Mapping\CountryCollection
        factory: [Phlexible\Bundle\CountryContextBundle\Mapping\CountryCollectionFactory, createCollection]
        arguments:
            - "%phlexible_country_context.countries%"

    phlexible_country_context.router.country_aware_request_matcher:
        class: Phlexible\Bundle\CountryContextBundle\Router\Handler\CountryAwareRequestMatcher
        public: false
        arguments:
            - "@logger"
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_siteroot.siteroot_request_matcher"
            - "%phlexible_cms.languages.available%"
            - "%phlexible_cms.languages.default%"
        tags:
            - {name: monolog.logger, channel: router}

    phlexible_country_context.router.country_aware_url_generator:
        class: Phlexible\Bundle\CountryContextBundle\Router\Handler\CountryAwareUrlGenerator
        public: false
        arguments:
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_siteroot.siteroot_hostname_generator"
        tags:
            - {name: monolog.logger, channel: router}

    phlexible_country_context.node_checker:
        class: Phlexible\Bundle\CountryContextBundle\Node\NodeChecker
        public: false
        arguments:
            - "@phlexible_country_context.country_context_manager"

    phlexible_country_context.node_countries_resolver:
        class: Phlexible\Bundle\CountryContextBundle\Node\NodeCountriesResolver
        public: false
        arguments:
            - "@phlexible_country_context.country_context_manager"
            - "@phlexible_country_context.country_collection"

    phlexible_country_context.element_mediator.country_aware_viewable_voter:
        class: Phlexible\Bundle\CountryContextBundle\Mediator\CountryAwareViewableVoter
        public: false
        arguments:
            - "@request_stack"
            - "@phlexible_country_context.node_checker"

    phlexible_country_context.node_url_generator.country_and_language:
        class: Phlexible\Bundle\CountryContextBundle\NodeUrlGenerator\CountryAndLanguageNodeUrlGenerator
        arguments:
            - "@phlexible_tree.content_tree_manager"
            - "@router"

    # events listeners
    phlexible_country_context.country_countext_listener:
        class: Phlexible\Bundle\CountryContextBundle\EventListener\CountryContextListener
        arguments:
            - "@phlexible_country_context.doctrine.country_context_manager"
            - "@phlexible_country_context.country_collection"
            - "@phlexible_country_context.node_checker"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_country_context.country_listener:
        class: Phlexible\Bundle\CountryContextBundle\EventListener\CountryListener
        arguments:
            - "@router"
            - "%phlexible_country_context.default_country%"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_country_context.document_listener:
        class: Phlexible\Bundle\CountryContextBundle\EventListener\DocumentListener
        arguments:
            - "@phlexible_country_context.node_countries_resolver"
        tags:
            - {name: kernel.event_subscriber}

    # twig extensions
    phlexible_country_context.twig.country_context_extension:
        class: Phlexible\Bundle\CountryContextBundle\Twig\Extension\CountryContextExtension
        arguments:
            - "@request_stack"
            - "@phlexible_country_context.country_collection"
        tags:
            - {name: twig.extension}

    # Indexer Parameters Generator
    phlexible_indexer_element.country_parameters_generator:
        class: Phlexible\Bundle\CountryContextBundle\Indexer\ParametersGenerator\CountryIndexerParametersGenerator
        arguments:
            - "@phlexible_country_context.country_collection"
        public: false
        tags:
            - {name: phlexible_indexer_page.param_generator, priority: 0}

