services:
    phlexible_country_context.country_collection:
        class: Phlexible\Bundle\CountryContextBundle\Mapping\CountryCollection
        factory: [Phlexible\Bundle\CountryContextBundle\Mapping\CountryCollectionFactory, createCollection]
        arguments:
            - %phlexible_country_context.countries%


    phlexible_country_context.router.handler.country_aware:
        class: Phlexible\Bundle\CountryContextBundle\Router\Handler\CountryAwareHandler
        arguments:
            - @logger
            - @phlexible_tree.content_tree_manager
            - @phlexible_siteroot.siteroot_request_matcher
            - @phlexible_siteroot.siteroot_hostname_generator
            - %phlexible_cms.languages.available%
            - %phlexible_cms.languages.default%
        tags:
            - {name: monolog.logger, channel: router}

    phlexible_country_context.mediator.element.viewable_voter.country_aware:
        class: Phlexible\Bundle\CountryContextBundle\Mediator\CountryAwareViewableVoter

    # events listeners
    phlexible_country_context.country_countext_listener:
        class: Phlexible\Bundle\CountryContextBundle\EventListener\CountryContextListener
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_country_context.country_collection
        tags:
            - {name: kernel.event_subscriber}

    phlexible_country_context.country_listener:
        class: Phlexible\Bundle\CountryContextBundle\EventListener\CountryListener
        arguments:
            - @router
            - en
        tags:
            - {name: kernel.event_subscriber}
